#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jansi
Version  : 1.17.1
Release  : 1
URL      : https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.17.1/jansi-1.17.1.jar
Source0  : https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.17.1/jansi-1.17.1.jar
Source1  : https://repo1.maven.org/maven2/org/fusesource/jansi/jansi-project/1.17.1/jansi-project-1.17.1.pom
Source2  : https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.17.1/jansi-1.17.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-jansi-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-jansi package.
Group: Data

%description data
data components for the mvn-jansi package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/jansi/jansi/1.17.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/jansi/jansi/1.17.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/jansi/jansi/1.17.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/jansi/jansi/1.17.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/fusesource/jansi/jansi-project/1.17.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/fusesource/jansi/jansi-project/1.17.1


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/fusesource/jansi/jansi-project/1.17.1/jansi-1.17.1.pom
/usr/share/java/.m2/repository/org/fusesource/jansi/jansi/1.17.1/jansi-1.17.1.jar
/usr/share/java/.m2/repository/org/fusesource/jansi/jansi/1.17.1/jansi-project-1.17.1.pom
